### ISSUE TITLE
qline with VIM 9.1.378 

### ISSUE THREAD

**Issue by Glog78** [Bakudankun/qline.vim#4]
Vim version: 9.1.378

I get the following errors:

```
Error detected while compiling function qline#Statusline[1]..<SNR>74_Statusline:
line    9:
E1048: Item not found in script: Get
```

Thank you for your plugin.

**Comment by Glog78** [comment]
can be closed ... it might be an issue between qline and vim9-jetpack. I changed back for Plug and everything is working now.

**Comment by Glog78** [comment]
Most likely not qline related

**Comment by Bakudankun** [comment]
Sorry for late reply.
I've also tried with latest vim and I got no problem.
Thank you for using my plugin!
